name: 💡 Feature Request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using the extension and considering suggesting an idea
  - type: textarea
    attributes:
      label: Describe the feature
      description: What would you like to see added / supported?
    validations:
      required: true
